### PR TITLE
Add support for .net standard

### PR DESCRIPTION
**Pull request by jcdekoning**
We are updating our projects to .net core, but are unable to use this library because it is compiles against .net 4.5.1. I made this PR which adds .net standard 1 and .net standard 2 as target framewors together with .net 4.5.1

I followed the recommendations as written here https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

The NimEngine is rewritten to the new SDK project file format.

Are you able to merge this PR in and publish a new version of this library. Make sure to use dotnet pack/publish so that the correct nuget package is created containing all target frameworks

### CODE REVIEW

**Review by hkhaug — APPROVED** [review]

**Comment by modestotech** [comment]
@hkhaug, I can't see that this has been published to nuget.org. I'm using this package in a .NET Core project and am getting warnings. The last update of the NuGet was in [2015](https://www.nuget.org/packages/nor-id-num). 

Have you solved it @jcdekoning? Maybe I'm using the wrong NuGet.

**Comment by jcdekoning** [comment]
@hkhaug it is indeed not published. That is something @hkhaug has to do. Would be great if he is able to do that. 

@hkhaug If you need help just let me know

**Comment by modestotech** [comment]
@hkhaug Will you look into this? Would be really great.

**Comment by hkhaug** [comment]
Hello!

Sure, I can publish – but I have no idea how. If you can help me that would be great.

Best regards,
Hans Kristian Haug

**Comment by jcdekoning** [comment]
@hkhaug Create a powershell script to get this published to nuget. You find it as PR https://github.com/hkhaug/nor-id-num/pull/6.

Version in csproj file is set to 1.0.4. I think this is fine. The new package should not break anything. But if you want, you can just bump it to new major version

**Pull request merged**
